'use client';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {PackageOpen} from 'lucide-react';
export function Choice({value,onChange,options,label,disabled=false}:{value:string;onChange:(s:string)=>void;options:{value:string;label:string}[];label:string;disabled?:boolean}){return <Select value={value||'all'} onValueChange={s=>onChange(s==='all'?'':s)} disabled={disabled}><SelectTrigger aria-label={label} className="choice"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value||'all'} key={o.value||'all'}>{o.label}</SelectItem>)}</SelectContent></Select>}
export function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description?:string;children:React.ReactNode;wide?:boolean}){return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className={'campus-modal '+(wide?'wide':'')}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description||'CampusLoop · Cộng đồng sinh viên'}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>}
export function Confirm({value,onClose}:{value:null|{title:string;body:string;action:()=>Promise<void>};onClose:()=>void}){return <AlertDialog open={!!value} onOpenChange={v=>!v&&onClose()}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{value?.title}</AlertDialogTitle><AlertDialogDescription>{value?.body}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Hủy</AlertDialogCancel><AlertDialogAction onClick={()=>{void value?.action();onClose()}}>Xác nhận</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
export function Empty({title,body,children}:{title:string;body:string;children?:React.ReactNode}){return <div className="empty-state"><PackageOpen size={40}/><h3>{title}</h3><p>{body}</p>{children}</div>}
export function LoginGate(){return <Empty title="Tham gia CampusLoop" body="Đăng nhập để đăng tin, lưu sản phẩm và kết nối với sinh viên khác."><a className="btn primary" href="/login?return_to=%2Fprofile">Đăng nhập CampusLoop</a></Empty>}