'use client';
import {useState} from 'react';
import {ArrowLeftRight,BookOpen,Shirt,Laptop,House,Gift,Search,ShoppingCart,Plus,Heart,MapPin,UserRound,Handshake,Star,ShieldCheck,Check,ChevronRight,ArrowRight} from 'lucide-react';
import {categories,money,modeLabel,Product} from '@/lib/catalog';
const icons:Record<string,any>={BookOpen,Shirt,Laptop,House,Gift,ArrowLeftRight};
export function ProductCard({product:p,onOpen,onSave}:{product:Product;onOpen:(p:Product)=>void;onSave:(p:Product)=>void}){
return <article className="product-card"><button className="product-photo" onClick={()=>onOpen(p)} aria-label={'Xem '+p.title}><img src={p.images[0]} alt={p.title} loading="lazy"/>{!p.sample&&<span className={'badge '+p.mode}>{modeLabel(p.mode)}</span>}</button><div className="product-info"><div className="product-title"><button onClick={()=>onOpen(p)}>{p.title}</button><button className={'heart '+(p.saved?'saved':'')} onClick={()=>onSave(p)} aria-label={(p.saved?'Bỏ lưu ':'Lưu ')+p.title}><Heart size={19} fill={p.saved?'currentColor':'none'}/></button></div><p className="price">{p.mode==='exchange'&&p.sample?'Cần đổi size M':money(p)}</p><p className="product-meta"><MapPin size={13}/>{p.location.split(',')[0]} · {p.sample?'Tin mẫu':'Mới đăng'}</p></div></article>}
export function HowItWorks({onAction}:{onAction:(view:string)=>void}){return <section className="how-card" id="how"><h2>CampusLoop hoạt động như thế nào?</h2><div className="steps">{[{icon:UserRound,title:'1. Đăng ký tài khoản',desc:'Xác minh sinh viên để đảm bảo an toàn',view:'profile'},{icon:Search,title:'2. Tìm kiếm sản phẩm',desc:'Dễ dàng lọc theo nhu cầu và khu vực',view:'browse'},{icon:Handshake,title:'3. Kết nối giao dịch',desc:'Liên hệ, thỏa thuận và giao dịch',view:'messages'},{icon:Star,title:'4. Đánh giá',desc:'Chia sẻ trải nghiệm và xây dựng cộng đồng uy tín',view:'profile'}].map(s=><div className="step" key={s.title}><button className="step-icon" aria-label={s.title} onClick={()=>onAction(s.view)}><s.icon size={24}/></button><div><strong>{s.title}</strong><p>{s.desc}</p></div></div>)}</div></section>}
export function Safety({onAction}:{onAction:(view:string)=>void}){return <section className="safety-card"><button className="safety-title" onClick={()=>onAction('safety')}><ShieldCheck size={24}/><h2>An toàn giao dịch</h2></button><ul>{['Xác thực tài khoản sinh viên','Đánh giá người dùng sau giao dịch','Báo cáo vi phạm dễ dàng','Khuyến khích giao dịch tại khu vực công cộng'].map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul></section>}
export function Marketplace({products,onOpen,onSave,onAction,onBrowse}:{products:Product[];onOpen:(p:Product)=>void;onSave:(p:Product)=>void;onAction:(v:string)=>void;onBrowse:(filter?:any)=>void}){
const[query,setQuery]=useState('');const active=products.filter(p=>p.status==='active');const latest=active.slice(0,5);const nearby=active.filter(p=>p.location.includes('HUIT')).slice(products.every(p=>p.sample)?5:0,products.every(p=>p.sample)?9:4);
return <><section className="hero"><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow">Nền tảng mua bán - trao đổi - tặng đồ cũ dành riêng cho sinh viên</p><h1><span>Campus</span>Loop</h1><p className="slogan">“Đồ cũ của bạn, giá trị mới của người khác.”</p><form className="hero-search" onSubmit={e=>{e.preventDefault();onBrowse({q:query})}}><Search size={22}/><input aria-label="Tìm sản phẩm" placeholder="Bạn đang tìm gì? (VD: sách, máy tính, quần áo...)" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit">Tìm kiếm</button></form><div className="actions">{[{icon:ShoppingCart,label:'Mua',sub:'Giá tốt, chất lượng',cls:'buy',view:'sale'},{icon:Plus,label:'Bán',sub:'Thanh lý dễ dàng',cls:'sell',view:'post'},{icon:ArrowLeftRight,label:'Trao đổi',sub:'Tối ưu giá trị sử dụng',cls:'swap',view:'exchange'},{icon:Gift,label:'Cho tặng',sub:'Lan tỏa yêu thương',cls:'give',view:'gift'}].map(a=><button className={'action '+a.cls} key={a.label} onClick={()=>a.view==='post'?onAction('post'):onBrowse({mode:a.view})}><a.icon size={34}/><div><strong>{a.label}</strong><span>{a.sub}</span></div></button>)}</div></div><div className="hero-art"><img src="/images/hero-illustration.png" alt="Ba sinh viên cùng xây dựng lối sống xanh, tái sử dụng và bảo vệ môi trường"/></div></div></section><main className="container home-main"><section><div className="section-head"><h2>Danh mục sản phẩm</h2><button onClick={()=>onBrowse()}>Xem tất cả <ArrowRight size={16}/></button></div><div className="categories">{categories.map(c=>{const Icon=icons[c.icon];return <button key={c.id} className={'category '+c.color} onClick={()=>onBrowse(c.id==='gift'||c.id==='exchange'?{mode:c.id}:{category:c.id})}><Icon size={40} strokeWidth={2.2}/><strong>{c.name}</strong><p>{c.description}</p></button>})}</div></section><div className="home-columns"><div className="main-column"><section><div className="section-head"><h2>Sản phẩm mới đăng</h2><button onClick={()=>onBrowse()}>Xem tất cả <ArrowRight size={16}/></button></div><div className="product-grid home-grid">{latest.map(p=><ProductCard key={p.id} product={p} onOpen={onOpen} onSave={onSave}/>)}</div></section><HowItWorks onAction={onAction}/></div><aside className="home-aside"><section className="nearby-card"><div className="nearby-head"><h2><MapPin size={22}/>Sản phẩm gần bạn</h2><button onClick={()=>onBrowse({location:'HUIT'})}>Xem tất cả <ArrowRight size={14}/></button></div><div className="nearby-list">{nearby.map(p=><button key={p.id} className="nearby-product" onClick={()=>onOpen(p)}><img src={p.images[0]} alt={p.title}/><div><strong>{p.title}</strong><span>{money(p)}</span><small><MapPin size={12}/>Khu vực HUIT</small></div><ChevronRight size={18}/></button>)}</div></section><Safety onAction={onAction}/></aside></div></main></>}