import {getSessionUser} from './auth';
import {database,bucket,one,rows,run} from './store';
import {ApiError} from './errors';
import {sampleProducts,categories} from './catalog';
export {database,bucket,one,rows,run,ApiError};
export const now=()=>new Date().toISOString();
export const uid=()=>crypto.randomUUID();
export async function current(required=false){const auth=await getSessionUser();if(!auth){if(required)throw new ApiError(401,'Vui lòng đăng nhập để tiếp tục.');return null}const p=await one('SELECT * FROM profiles WHERE id=?',auth.userId);if(!p)throw new ApiError(503,'Không thể tải tài khoản.');if(p.blocked)throw new ApiError(403,'Tài khoản đang bị khóa. Vui lòng liên hệ quản trị viên.');return {...p,role:auth.role};}
export async function admin(){const p=await current(true);if(p.role!=='admin')throw new ApiError(403,'Chỉ quản trị viên được thực hiện thao tác này.');return p}
export function txt(x:unknown,max=3000,min=0){if(typeof x!=='string')throw new ApiError(400,'Thông tin không hợp lệ.');const v=x.trim();if(v.length<min||v.length>max)throw new ApiError(400,'Nội dung cần có từ '+min+' đến '+max+' ký tự.');return v}
export const safeProfile=(p:any)=>({id:p.id,name:p.name,school:p.school,bio:p.bio,avatar:p.avatar,verified:p.verified});
export const parsed=(p:any)=>({...p,images:JSON.parse(p.images||'[]'),saved:!!p.saved});
export const listingSql="SELECT l.*,p.name owner_name,p.verified,coalesce((SELECT avg(score) FROM reviews WHERE target_id=l.owner_id),0) rating,(SELECT count(*) FROM reviews WHERE target_id=l.owner_id) review_count FROM listings l JOIN profiles p ON p.id=l.owner_id";
export async function listing(id:string,viewer?:any){const p=await one(listingSql+' WHERE l.id=?',id);if(!p||p.status==='deleted'||(['hidden','moderated'].includes(p.status)&&viewer?.id!==p.owner_id&&viewer?.role!=='admin'))throw new ApiError(404,'Tin không còn hiển thị.');const owner=await one('SELECT blocked FROM profiles WHERE id=?',p.owner_id);if(owner?.blocked&&viewer?.role!=='admin'&&viewer?.id!==p.owner_id)throw new ApiError(404,'Tin không còn hiển thị.');return parsed(p)}
export async function seed(){await run("INSERT OR IGNORE INTO profiles (id,email,name,created_at) VALUES ('sample','','CampusLoop · Tin mẫu',?)",now());await database().batch([...categories.filter(c=>!['gift','exchange'].includes(c.id)).map(c=>database().prepare('INSERT OR IGNORE INTO categories (id,name) VALUES (?,?)').bind(c.id,c.name)),...sampleProducts.map(p=>database().prepare('INSERT OR IGNORE INTO listings (id,owner_id,title,category,mode,price,condition,description,location,images,status,sample,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(p.id,p.owner_id,p.title,p.category,p.mode,p.price,p.condition,p.description,p.location,JSON.stringify(p.images),p.status,1,p.created_at))]);}
export async function validateListing(b:any,user:any){const title=txt(b.title,100,4),description=txt(b.description,4000,10),location=txt(b.location,120,3);if(!await one('SELECT id FROM categories WHERE id=?',b.category))throw new ApiError(400,'Danh mục không hợp lệ.');if(!['sale','exchange','gift'].includes(b.mode)||!['Mới','Còn tốt','Đã qua sử dụng'].includes(b.condition))throw new ApiError(400,'Hình thức hoặc tình trạng không hợp lệ.');const price=b.mode==='sale'?Number(b.price):0;if(!Number.isInteger(price)||price<0||price>100000000||b.mode==='sale'&&price<1000)throw new ApiError(400,'Giá bán cần từ 1.000 đến 100.000.000 đ.');if(!Array.isArray(b.images)||b.images.length<1||b.images.length>6)throw new ApiError(400,'Cần từ 1 đến 6 ảnh sản phẩm.');for(const image of b.images){if(typeof image!=='string'||!image.startsWith('/api/files/'))throw new ApiError(400,'Vui lòng tải ảnh sản phẩm lên.');const f=await one("SELECT key FROM uploads WHERE key=? AND owner_id=? AND kind='listing'",image.slice('/api/files/'.length),user.id);if(!f)throw new ApiError(400,'Ảnh sản phẩm không hợp lệ.')}return {title,description,location,category:b.category,mode:b.mode,condition:b.condition,price,images:JSON.stringify(b.images)}}
export async function conversation(id:string,user:any){const c=await one('SELECT * FROM conversations WHERE id=? AND (buyer_id=? OR seller_id=?)',id,user.id,user.id);if(!c)throw new ApiError(404,'Không tìm thấy cuộc trò chuyện.');return c}
export async function deal(id:string,user:any){const d=await one('SELECT * FROM deals WHERE id=? AND (buyer_id=? OR seller_id=?)',id,user.id,user.id);if(!d)throw new ApiError(404,'Không tìm thấy giao dịch.');return d}
export async function limit(table:string,column:string,id:string,max:number){const result=await one('SELECT count(*) n FROM '+table+' WHERE '+column+'=? AND created_at>?',id,new Date(Date.now()-3600000).toISOString());if(result.n>=max)throw new ApiError(429,'Bạn thao tác quá nhiều. Vui lòng thử lại sau.')}
export function guardOrigin(req:Request){const origin=req.headers.get('origin');if(req.headers.get('sec-fetch-site')==='cross-site'||origin&&origin!==new URL(req.url).origin)throw new ApiError(403,'Yêu cầu không hợp lệ.');}